### ISSUE TITLE
Обратная связь

### ISSUE THREAD

**Issue by wpfdev** [MoseykoEng/animation-library#1]
Добрый день, как с вами связаться в telegram/по email насчет вакансии программиста-стажера?

**Comment by wpfdev** [comment]
#junior #php #фултайм #офис #продуктовая_команда 
Ищем помощников на проект по разработке облачной CRM для бронирования отелей.
Требование: образование техническое, средне-специальное либо не оконченное высшее. Можно студентам без опыта работы но с желанием развиваться в веб-разработке.
Обязательно понимание основ HTML, CSS, JavaScript, PHP
Будет плюсом: опыт программирования на любом языке программирования высокого уровня, знание SQL
Ожидаем от кандидата: желание обучаться программированию, интерес к новым технологиям и карьерному росту в IT сфере.
Условия на испытательный срок: гибкий график, 2-3 рабочих дня в неделю с 10 до 17, офис в центре города, оплата еженедельно
Резюме присылайте мне в телеграм  https://t.me/appsmaker

**Comment by MoseykoEng** [comment]
Здравствуйте, мой телеграмм: @eneroplОтправлено с моего телефона Huawei-------- Исходное сообщение --------От: wpfdev <notifications@github.com>Дата: пт, 29 янв. 2021 г., 09:03Кому: MoseykoEng/animation-library <animation-library@noreply.github.com>Копия: Subscribed <subscribed@noreply.github.com>Тема: [MoseykoEng/animation-library] Обратная связь (#1)

Добрый день, как с вами связаться в telegram/по email насчет вакансии программиста-стажера?
